### ISSUE TITLE
Goethe not self-bootstrapping when used with gradle 7.3.1

### ISSUE THREAD

**Issue by raiju** [palantir/goethe#91]
Getting the following failure when running goethe in JDK 17 with Gradle 7.3.1:
```
Caused by: com.palantir.goethe.GoetheException: Formatter exited non-zero (1) formatting class $CLASSNAME:
Error: Could not find or load main class com.palantir.goethe.GoetheMain
Caused by: java.lang.ClassNotFoundException: com.palantir.goethe.GoetheMain

        at com.palantir.goethe.BootstrappingFormatterFacade.formatSource(BootstrappingFormatterFacade.java:66)
        at com.palantir.goethe.Goethe.formatAsString(Goethe.java:54)
        at com.palantir.goethe.Goethe.formatAndEmit(Goethe.java:97)
        at com.palantir.conjure.java.GenerationCoordinator.lambda$emit$1(GenerationCoordinator.java:46)
        at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:250)
        at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:240)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
```

After attaching a debugger, it looks like the classpath isn't set right, as `System.getProperty("java.class.path")` returns:
```
~/.gradle/wrapper/dists/gradle-7.3.1-bin/[...]/gradle-7.3.1/lib/gradle-launcher-7.3.1.jar
```

**Comment by raiju** [comment]
Should be fixed in https://github.com/palantir/goethe/pull/93
